import type { Post, Achievement, PRData, LeaderboardEntry } from "./types"

export const mockPosts: Post[] = [
  {
    id: "1",
    userId: "1",
    content:
      "Just shipped a new feature using Next.js 15! The performance improvements are incredible. Check out this dashboard we built!",
    image: "/modern-web-dashboard-interface.jpg",
    createdAt: new Date("2024-03-15T10:30:00"),
    likes: 24,
    comments: 5,
  },
  {
    id: "2",
    userId: "2",
    content:
      "Working on a new open source project. Excited to share it with the community soon! Here's a sneak peek of the UI.",
    image: "/code-editor-interface-dark-theme.jpg",
    createdAt: new Date("2024-03-14T15:20:00"),
    likes: 18,
    comments: 3,
  },
  {
    id: "3",
    userId: "3",
    content: "Learned something new about React Server Components today. The mental model is finally clicking!",
    createdAt: new Date("2024-03-13T09:15:00"),
    likes: 32,
    comments: 8,
  },
  {
    id: "4",
    userId: "4",
    content: "Built this amazing landing page for a client. What do you think?",
    image: "/modern-landing-page.png",
    createdAt: new Date("2024-03-12T14:45:00"),
    likes: 45,
    comments: 12,
  },
  {
    id: "5",
    userId: "5",
    content: "Coffee and code - the perfect combination for a productive morning!",
    image: "/coffee-laptop-workspace-desk.jpg",
    createdAt: new Date("2024-03-11T08:20:00"),
    likes: 67,
    comments: 15,
  },
]

export const mockAchievements: Achievement[] = [
  {
    id: "1",
    userId: "1",
    title: "First PR Merged",
    description: "Successfully merged your first pull request",
    icon: "🎉",
    earnedAt: new Date("2024-01-15"),
    isSystemGenerated: true,
  },
  {
    id: "2",
    userId: "1",
    title: "10 PRs Milestone",
    description: "Merged 10 pull requests",
    icon: "⭐",
    earnedAt: new Date("2024-02-20"),
    isSystemGenerated: true,
  },
  {
    id: "3",
    userId: "1",
    title: "Code Contributor",
    description: "Contributed to 5 different repositories",
    icon: "💻",
    earnedAt: new Date("2024-03-01"),
    isSystemGenerated: true,
  },
  {
    id: "4",
    userId: "1",
    title: "Community Helper",
    description: "Helped 10 developers with code reviews",
    icon: "🤝",
    earnedAt: new Date("2024-03-10"),
    isSystemGenerated: true,
  },
  {
    id: "5",
    userId: "2",
    title: "100 Commits Milestone",
    description: "Reached 100 commits across all repositories",
    icon: "🔥",
    earnedAt: new Date("2024-03-08"),
    isSystemGenerated: true,
  },
  {
    id: "6",
    userId: "3",
    title: "Bug Hunter",
    description: "Fixed 20 critical bugs",
    icon: "🐛",
    earnedAt: new Date("2024-03-05"),
    isSystemGenerated: true,
  },
]

export const mockPRData: PRData[] = [
  { date: "2024-01", count: 3 },
  { date: "2024-02", count: 5 },
  { date: "2024-03", count: 8 },
  { date: "2024-04", count: 6 },
  { date: "2024-05", count: 10 },
  { date: "2024-06", count: 12 },
  { date: "2024-07", count: 9 },
  { date: "2024-08", count: 15 },
  { date: "2024-09", count: 11 },
  { date: "2024-10", count: 14 },
  { date: "2024-11", count: 13 },
  { date: "2024-12", count: 16 },
]

export const mockLeaderboard: LeaderboardEntry[] = [
  {
    userId: "1",
    username: "demo_user",
    name: "Demo User",
    avatar: "/developer-avatar.png",
    prs: 122,
    rank: 1,
  },
  {
    userId: "2",
    username: "sarah_dev",
    name: "Sarah Johnson",
    avatar: "/female-developer-avatar.png",
    prs: 108,
    rank: 2,
  },
  {
    userId: "3",
    username: "mike_codes",
    name: "Mike Chen",
    avatar: "/male-developer-avatar.png",
    prs: 95,
    rank: 3,
  },
  {
    userId: "4",
    username: "alex_tech",
    name: "Alex Rodriguez",
    avatar: "/developer-profile.png",
    prs: 87,
    rank: 4,
  },
  {
    userId: "5",
    username: "emma_builds",
    name: "Emma Wilson",
    avatar: "/female-coder-avatar.jpg",
    prs: 76,
    rank: 5,
  },
]
